name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Build project
        run: dotnet build --configuration Release
